<a href="https://colab.research.google.com/github/istabrak-abbes/Gender-By-Name-approachs/blob/main/name_gender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np
df = pd.read_csv("name_gender_dataset.csv")

In [32]:

df=df.drop(columns=['Probability','Count'])


In [33]:
df.tail()

Name Gender
147264  Zylenn      M
147265  Zymeon      M
147266  Zyndel      M
147267  Zyshan      M
147268   Zyton      M

In [34]:
df.Gender.value_counts()

F    89749
M    57520
Name: Gender, dtype: int64

In [35]:
df.isnull().isnull().sum()

Name      0
Gender    0
dtype: int64

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [37]:
df.Gender.replace({'F':0, 'M':1},inplace=True)

In [38]:
df.Gender.unique()

array([1, 0])

In [39]:
Xsimples =df['Name']

In [40]:
vect = CountVectorizer()
X = vect.fit_transform(Xsimples)

In [41]:
from sklearn.model_selection import train_test_split 
Ysimples = df['Gender']
X_train, X_test, y_train, y_test = train_test_split(X, Ysimples, test_size=0.1, random_state=42)

In [42]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.5516398451823182

In [43]:
# Accuracy of our Model
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")

Accuracy of Model 55.16398451823182 %


In [44]:
# Accuracy of our Model
print("Accuracy of Model",clf.score(X_train,y_train)*100,"%")

Accuracy of Model 91.50910654735857 %


Sample Prediction

In [45]:
# Sample1 Prediction
sample_name = ["Mary"]
name_to_vect = vect.transform(sample_name).toarray()

In [46]:
name_to_vect

array([[0, 0, 0, ..., 0, 0, 0]])

In [47]:
clf.predict(name_to_vect)

array([0])

In [49]:
# Sample2 Prediction
sample_name1 = ["Mark"]
vect1 = vect.transform(sample_name1).toarray()
clf.predict(vect1)

array([1])

In [52]:
# A function to do it
def genderpredictor(a):
    test_name = [a]
    vector = vect.transform(test_name).toarray()
    if clf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")

In [53]:
genderpredictor('Ista')

Female
